### ISSUE TITLE
User Error

### ISSUE THREAD

**Issue by Dejulia489** [wmlutz/gatsby-source-dynamodb#3]
I am getting the following error when I try to run develop. I assume it is user error, however I can't find any starters or examples for this plugin. If you could point me in the right direction, I would be happy to write up a blog post you can link to in your read me if you are interested. 

> ReferenceError: params is not defined
>     at Response.onScan (C:\git\gatsby-starter-default\node_modules\gatsby-source-dynamodb\gatsby-node.js:47:11)
>     at Request.<anonymous> (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\request.js:364:18)
>     at Request.callListeners (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
>     at Request.emit (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
>     at Request.emit (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\request.js:683:14)
>     at Request.transition (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\request.js:22:10)
>     at AcceptorStateMachine.runTo (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\state_machine.js:14:12)
>     at C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\state_machine.js:26:10
>     at Request.<anonymous> (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\request.js:38:9)
>     at Request.<anonymous> (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\request.js:685:12)
>     at Request.callListeners (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
>     at Request.emit (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
>     at Request.emit (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\request.js:683:14)
>     at Request.transition (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\request.js:22:10)
>     at AcceptorStateMachine.runTo (C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\state_machine.js:14:12)
>     at C:\git\gatsby-starter-default\node_modules\aws-sdk\lib\state_machine.js:26:10

What should the valiue for typename be?

Plugin config:
```
{
      resolve: 'gatsby-source-dynamodb',
      options: {
        typeName: 'payload',
        accessKeyId: process.env.AWS_ACCESS_KEY_ID, 
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        region: 'us-west-2',
        params: {
          TableName : "myTable"
        }
      }
    },

```
Any help would be appreciated.

Thanks

Edit: code formatting

**Comment by Eyad-Alama** [comment]
Getting the exact same error, has this been resolved or anything ? 
Thanks !

**Comment by jacknugent** [comment]
This is not user error -- `params` is always not defined. I created a [PR to address the issue](https://github.com/wmlutz/gatsby-source-dynamodb/pull/5). In `gatsby-source-dynamodb`, you need to change `params` to `options.params` and the plugin will implement paging correctly.
